# Email settings

import os

AUTHEMAIL_EMAIL_FROM = os.environ.get('AUTHEMAIL_DEFAULT_EMAIL_FROM') or '<YOUR DEFAULT_EMAIL_FROM HERE>'
AUTHEMAIL_EMAIL_BCC = os.environ.get('AUTHEMAIL_DEFAULT_EMAIL_BCC') or '<YOUR DEFAULT_EMAIL_BCC HERE>'

AUTHEMAIL_EMAIL_HOST = os.environ.get('AUTHEMAIL_EMAIL_HOST') or '<YOUR EMAIL_HOST HERE>'
AUTHEMAIL_EMAIL_PORT = os.environ.get('AUTHEMAIL_EMAIL_PORT') or 0
AUTHEMAIL_EMAIL_HOST_USER = os.environ.get('AUTHEMAIL_EMAIL_HOST_USER') or '<YOUR EMAIL_HOST_USER HERE>'
AUTHEMAIL_EMAIL_HOST_PASSWORD = os.environ.get('AUTHEMAIL_EMAIL_HOST_PASSWORD') or '<YOUR EMAIL_HOST_PASSWORD HERE>'
AUTHEMAIL_EMAIL_USE_TLS = True
AUTHEMAIL_EMAIL_USE_SSL = False
