# Generated by Django 3.1 on 2021-05-18 23:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authemail", "0002_emailchangecode"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAgent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.BinaryField(
                        max_length=128, unique=True, verbose_name="identifier"
                    ),
                ),
                ("ua_string", models.TextField(verbose_name="user agent string")),
            ],
        ),
        migrations.CreateModel(
            name="AuthAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("RESET_PASSWORD_REQ", "Password reset request"),
                            ("PASSWORD_UPDATED", "Password has been changed"),
                            (
                                "CHANGE_EMAIL_REQ",
                                "A request to change email has been submitted",
                            ),
                            (
                                "EMAIL_UPDATED",
                                "The email associated with the account has been updated",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ipaddr",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="ip address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authemail.useragent",
                    ),
                ),
            ],
            options={
                "verbose_name": "AuditLog",
                "verbose_name_plural": "AuditLogs",
            },
        ),
    ]
