# Generated by Django 3.1 on 2021-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authemail", "0003_authauditlog_useragent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SIGNUP", "New account signup"),
                    ("LOGIN", "Login"),
                    ("RESET_PASSWORD_REQ", "Password reset request"),
                    ("PASSWORD_UPDATED", "Password has been changed"),
                    (
                        "CHANGE_EMAIL_REQ",
                        "A request to change email has been submitted",
                    ),
                    (
                        "EMAIL_UPDATED",
                        "The email associated with the account has been updated",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
