# Generated by Django 3.2 on 2021-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authemail", "0004_auto_20210519_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useragent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
