# Generated by Django 3.2 on 2021-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authemail", "0006_auto_20210521_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="useragent",
            name="browser_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useragent",
            name="browser_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="useragent",
            name="device_brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useragent",
            name="device_family",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="useragent",
            name="device_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="useragent",
            name="os_family",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useragent",
            name="os_version",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
